server:
  port: 8002
spring:
  application:
    name: payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///cloud?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.hezhi3f.entity
eureka:
  instance:
    instance-id: payment-8002
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      #defaultZone: http://localhost:4444/eureka
      defaultZone: http://eureka4444.com:4444/eureka,http://eureka4445.com:4445/eureka